version: '3'

services:
  pricecalculator:
    image: 'pricecalculator:latest'
    container_name: 'pricecalculator'
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres
    depends_on:
      - database

  database:
    image: 'postgres:16'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pricecalculator
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin4'
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: username@example.com
      PGADMIN_DEFAULT_PASSWORD: password
  liquibase:
    image: 'liquibase/liquibase:4.23'
    container_name: 'liquibase'
    volumes:
      - ./database/changelog.yml:/liquibase/changelog.yml
      - ./database/migrations:/liquibase/migrations
      - ./database/liquibase.properties:/liquibase.properties
    depends_on:
      - database
    command:
      - '--defaults-file=/liquibase.properties'
      - 'update'
networks:
  default:
    name: pricecalculator