spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/pricecalculator
    password: password
    username: user
---
spring:
  liquibase:
    change-log: changelog.yml
  config:
    activate:
      on-profile: test